### PR TITLE
move to mathjax-node-sre

### PR DESCRIPTION
**Pull request by pkra**
Updates to speech-rule-engine v2 and mathjax-node v1

### CODE REVIEW

**Comment by pkra** [comment]
@tiarno ping?

**Comment by tiarno** [comment]
Thanks for the fix @pkra, and sorry for the delay. Work...

**Comment by pkra** [comment]
No problem at all!

**Comment by pkra** [comment]
Will you make a release? (Have you thought about automating releases to npm using travis.ci?)

**Comment by tiarno** [comment]
just did a release. 
I'm looking at automation too, but it looks like npm is just pointing here (I think).

**Comment by pkra** [comment]
> just did a release.

Thanks!

> I'm looking at automation too, but it looks like npm is just pointing here (I think).

I'm not sure what you mean.

But to clarify what I meant: I was thinking of setting up a continuuous integration service to publish releases whenever a release is tagged here on the github repo (e.g. https://docs.travis-ci.com/user/deployment/npm/). Happy to help with that.

**Comment by tiarno** [comment]
hi @pkra, I bumped the patch number and republished on npm. I don't know how the ci stuff works, but if you have time, I'd appreciate your help. For now at least, I think the npm and github repos are in sync. thanks!

**Comment by pkra** [comment]
Thanks, @tiarno. 

The easiest way is to install the travis CLI tool and run `travis setup npm` which walks you through the setup. (And sign into Travis using GitHub to give Travis the necessary access.)

You could also add me to the repo as a maintainer, which should allow me to set up Travis through my own travis account.

**Comment by tiarno** [comment]
Thanks @pkra. I added you as a collaborator and I'll buy you a beer the next time I see you in real life. I appreciate your help!

**Comment by pkra** [comment]
Hm. I still can't set up travis; looks like I don't have the right permissions. I think I'd need admin rights (I understand if that's not ok with you). I'll try to find the time to make a PR to get you started instead..

**Comment by tiarno** [comment]
I didn't see any way to add except as a collaborator. Still, you've inspired me to learn more about travis-ci and I've made a little headway there (the connection exists, but not the yml file yet).
Thanks, I'll get it set.

**Comment by pkra** [comment]
That's great to hear. Here's my usual setup https://github.com/pkra/mathjax-node-page/blob/master/.travis.yml

**Pull request merged**
